permalink: pretty
markdown: kramdown
exclude: ["_posts-imported", "_posts-unpublished", "vendor", "node_modules"]
highlighter: pygments
plugins: [jekyll-paginate]
paginate: 8
safe: false
incremental: true
production_url : https://jakut.is
url : https://jakut.is
title : Vytautas Jakutis
author :
  name : Vytautas Jakutis
  email : vytautas@jakut.is
  github : jakutis
  twitter : jakutis0
