permalink: /:categories/:year/:month/:day/:title

exclude: ["_posts-imported"]
auto: true
pygments: true
paginate: 3
safe: true
production_url : https://jakut.is
url : https://jakut.is
title : Vytautas Jakutis
author :
  name : Vytautas Jakutis
  email : vytautas@jakut.is
  github : tahu
  twitter : tahu
