permalink: /:categories/:year/:month/:day/:title
markdown: kramdown
exclude: ["_posts-imported", "_posts-unpublished", "vendor"]
highlighter: pygments
gems: [jekyll-paginate]
paginate: 5
safe: false
production_url : https://jakut.is
url : https://jakut.is
title : Vytautas Jakutis
author :
  name : Vytautas Jakutis
  email : vytautas@jakut.is
  github : jakutis
  twitter : jakutis0
